name: Release

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

  build:
    needs: create-release
    strategy:
      matrix:
        platform: [
          'linux-arm',
          'linux-arm64',
          'linux-x64',
          'darwin-x64',
        ]
        pair: [
          'python:3.7',
          'python:3.8',
          'python:3.9',
        ]
        include:
          - platform: 'linux-arm'
            host-os: 'ubuntu-latest'
          - platform: 'linux-arm64'
            host-os: 'ubuntu-latest'
          - platform: 'linux-x64'
            host-os: 'ubuntu-latest'
          - platform: 'darwin-x64'
            host-os: 'macos-latest'
          - pair: 'python:3.7'
            language: 'python'
            version: '3.7'
          - pair: 'python:3.8'
            language: 'python'
            version: '3.8'
          - pair: 'python:3.9'
            language: 'python'
            version: '3.9'

    runs-on: ${{ matrix.host-os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Python ${{ matrix.version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Build adapter
      run: |
        ./build.sh "${{ matrix.platform }}" "${{ matrix.language }}" "${{ matrix.version }}"
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.tgz
          *.tgz.sha256sum
